#!/usr/bin/env python
"""Generate a local Markdown release draft without mutating release surfaces."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import release_audit  # noqa: E402


DEFAULT_RELEASE_AUDIT_JSON = Path("build/release_audit.json")
DEFAULT_PUBLISH_READINESS_JSON = Path("build/publish_readiness.json")
CLAIM_LEDGER_PATH = Path("docs/claims/public_claim_ledger.json")
CHANGELOG_PATH = Path("CHANGELOG.md")


def generate_release_draft(
    *,
    root: Path,
    version: str,
    release_audit_json: Path = DEFAULT_RELEASE_AUDIT_JSON,
    publish_readiness_json: Path = DEFAULT_PUBLISH_READINESS_JSON,
    refresh_reports: bool = True,
) -> str:
    changelog = (root / CHANGELOG_PATH).read_text(encoding="utf-8")
    ledger = _load_json(root / CLAIM_LEDGER_PATH)
    if refresh_reports:
        audit, readiness = _fresh_reports(root)
    else:
        audit = _load_json(_resolve(root, release_audit_json))
        readiness = _load_json(_resolve(root, publish_readiness_json))
    reference = _load_json(root / "examples" / "reference" / "reference_artifact.json")
    manifest = _load_json(root / "examples" / "reference" / "golden_manifest.json")

    return render_release_draft(
        version=version,
        changelog_entry=_extract_changelog_entry(changelog, version),
        ledger=ledger,
        audit=audit,
        readiness=readiness,
        reference=reference,
        manifest=manifest,
    )


def render_release_draft(
    *,
    version: str,
    changelog_entry: str,
    ledger: dict[str, Any],
    audit: dict[str, Any],
    readiness: dict[str, Any],
    reference: dict[str, Any],
    manifest: dict[str, Any],
) -> str:
    release_state = _release_state(audit, version)
    checks = _checks_by_id(audit)
    blocking = [check for check in audit.get("checks", []) if check.get("blocking")]
    warnings = [check for check in audit.get("checks", []) if check.get("status") == "WARNING"]
    lines = [
        f"# omegaprompt {version} Release Draft",
        "",
        "<!-- generated by tools/generate_release_draft.py; Markdown only; no release surfaces mutated -->",
        "",
        "## Status",
        "",
        f"- Publish readiness: `{readiness.get('final_status', 'UNKNOWN')}`",
        f"- Release audit: `{audit.get('final_status', 'UNKNOWN')}`",
        f"- PyPI publish performed by this generator: `false`",
        f"- Git tags created or pushed by this generator: `false`",
        f"- GitHub Release created or edited by this generator: `false`",
        "",
        "## Release State Visibility",
        "",
        f"- Local tag `{release_state['tag']}`: `{release_state['local_tag']}`",
        f"- GitHub Release marker: `{release_state['github_release_marker']}`",
        f"- PyPI state: `not queried; no publish performed`",
        f"- Release-state check: `{release_state['check_status']}`",
        "",
        "## Changelog",
        "",
        changelog_entry.strip() or f"No CHANGELOG entry found for `{version}`.",
        "",
        "## Deterministic Artifact References",
        "",
        "- Reference artifact: `examples/reference/reference_artifact.json`",
        "- Golden manifest: `examples/reference/golden_manifest.json`",
        "- Reproduce command: `python examples/reference/reproduce_reference_artifact.py`",
        "- Check command: `omegaprompt check-artifact examples/reference/reference_artifact.json --strict`",
        f"- Artifact schema version: `{reference.get('schema_version', 'unknown')}`",
        f"- Artifact status: `{reference.get('status', 'unknown')}`",
        f"- Ship recommendation: `{reference.get('ship_recommendation', 'unknown')}`",
        f"- Golden cases: `{_manifest_case_ids(manifest)}`",
        "",
        "## Claim Evidence",
        "",
        f"- Claim ledger: `{CLAIM_LEDGER_PATH.as_posix()}`",
        f"- Generated claim doc: `{ledger.get('generated_doc', 'docs/claims/README_CLAIMS.generated.md')}`",
        "- Public claims remain limited to ledger-backed source-of-truth, generated docs, reproducible commands, deterministic artifacts, or qualitative markers.",
        "- Unsupported download/adoption counts and provider/model/prompt superiority claims are not introduced by this draft.",
        "",
        "## Verification Commands",
        "",
        "```bash",
        "python tools/check_repo_consistency.py --strict",
        "python tools/generate_readme_claims.py --check",
        "python tools/reproduce_golden_reference.py --check",
        "omegaprompt check-artifact examples/reference/reference_artifact.json --strict",
        "python tools/release_audit.py --strict",
        "python tools/publish_readiness.py --strict --json-output build/publish_readiness.json",
        "python -m pytest -q",
        "```",
        "",
        "## Known Limitations",
        "",
    ]
    limitations = _known_limitations(blocking, warnings)
    lines.extend(limitations or ["- None reported by the local audit JSON."])
    lines.extend(
        [
            "",
            "## Gate Snapshot",
            "",
        ]
    )
    for check_id in (
        "VERSION_ALIGNMENT",
        "CLAIM_LEDGER_VALID",
        "README_CLAIMS_FRESH",
        "REFERENCE_ARTIFACTS_FRESH",
        "REFERENCE_ARTIFACT_INTEGRITY",
        "PROVIDER_DOCS_CODE_CONSISTENCY",
        "README_BADGE_COMPOSITION",
        "DEFAULT_CI_NO_LIVE_TESTS",
        "WHEEL_BUILD",
        "WHEEL_SMOKE_CORE",
        "WHEEL_SMOKE_MCP",
    ):
        check = checks.get(check_id)
        if check is not None:
            lines.append(f"- `{check_id}`: `{check.get('status')}`")
    lines.extend(
        [
            "",
            "## Scope Freeze Confirmation",
            "",
            "- No dashboard or web app scope is included.",
            "- No live provider tests are required by default.",
            "- No artifact schema, provider capability, train/test, KC4, gate, diff, guarded/expedition, or MCP optional-extra boundary is weakened by this draft.",
            "- This generator does not create a GitHub Release, push tags, or publish packages.",
            "",
        ]
    )
    return "\n".join(lines)


def _fresh_reports(root: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    audit = release_audit.run_release_audit(root)
    readiness = {
        "schema_version": "1.0",
        "tool": "tools/publish_readiness.py",
        "root": audit["root"],
        "final_status": audit["final_status"],
        "summary": audit["summary"],
        "release_audit": audit,
        "mutations": {
            "pypi_publish": False,
            "git_tags_created": False,
            "git_tags_pushed": False,
            "github_releases_created_or_edited": False,
        },
    }
    # Round-trip through JSON so the renderer sees the same primitive shape as
    # it would from persisted release audit / publish readiness reports.
    audit_json = json.loads(json.dumps(audit, sort_keys=True))
    readiness_json = json.loads(json.dumps(readiness, sort_keys=True))
    return audit_json, readiness_json


def _extract_changelog_entry(text: str, version: str) -> str:
    pattern = re.compile(
        rf"^## \[{re.escape(version)}\][^\n]*\n(?P<body>.*?)(?=^## \[|\Z)",
        flags=re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    return match.group("body").strip() if match else ""


def _release_state(audit: dict[str, Any], version: str) -> dict[str, str]:
    check = _checks_by_id(audit).get("GIT_TAG_RELEASE_STATE", {})
    details = check.get("details") or {}
    tag = str(details.get("tag") or f"v{version}")
    local_tag = "present" if details.get("local_tag_exists") is True else "absent"
    marker = "present" if details.get("release_marker") else "missing"
    return {
        "tag": tag,
        "local_tag": local_tag,
        "github_release_marker": marker,
        "check_status": str(check.get("status", "UNKNOWN")),
    }


def _checks_by_id(report: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        str(check.get("id")): check
        for check in report.get("checks", [])
        if isinstance(check, dict) and check.get("id")
    }


def _known_limitations(blocking: list[dict[str, Any]], warnings: list[dict[str, Any]]) -> list[str]:
    items: list[str] = []
    for check in blocking + warnings:
        message = str(check.get("message", "")).strip()
        status = str(check.get("status", "UNKNOWN"))
        check_id = str(check.get("id", "UNKNOWN"))
        if message:
            items.append(f"- `{check_id}` is `{status}`: {message}")
    return items


def _manifest_case_ids(manifest: dict[str, Any]) -> str:
    cases = manifest.get("cases")
    if not isinstance(cases, list):
        return "unknown"
    ids = [str(case.get("case_id")) for case in cases if isinstance(case, dict) and case.get("case_id")]
    return ", ".join(sorted(ids)) if ids else "unknown"


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve(root: Path, path: Path) -> Path:
    return path if path.is_absolute() else root / path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a local Markdown release draft without publishing.")
    parser.add_argument("--version", required=True, help="Release version, for example 1.7.4.")
    parser.add_argument("--output", type=Path, required=True, help="Markdown output path.")
    parser.add_argument("--release-audit-json", type=Path, default=DEFAULT_RELEASE_AUDIT_JSON)
    parser.add_argument("--publish-readiness-json", type=Path, default=DEFAULT_PUBLISH_READINESS_JSON)
    parser.add_argument(
        "--no-refresh-reports",
        action="store_true",
        help="Read existing audit/readiness JSON instead of generating fresh local reports first.",
    )
    args = parser.parse_args(argv)

    root = Path.cwd().resolve()
    markdown = generate_release_draft(
        root=root,
        version=args.version,
        release_audit_json=args.release_audit_json,
        publish_readiness_json=args.publish_readiness_json,
        refresh_reports=not args.no_refresh_reports,
    )
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
